/*
 * CategorizedInfoTestFrame.java
 *
 * Created on 03. Februar 2004, 09:50
 */

package wodka.test;

/**
 *
 * @author  __USER__
 */
public class CategorizedInfoTestFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /** Creates new form CategorizedInfoTestFrame */
    public CategorizedInfoTestFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonsPanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        categorizedInfoPanel1 = new wodka.view.CategorizedInfoPanel();

        setTitle("Test Frame");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm();
            }
        });

        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        updateButton.setText("update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed();
            }
        });

        buttonsPanel.add(updateButton);

        getContentPane().add(buttonsPanel, java.awt.BorderLayout.NORTH);

        getContentPane().add(categorizedInfoPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void updateButtonActionPerformed() {//GEN-FIRST:event_updateButtonActionPerformed
        this.categorizedInfoPanel1.updateViewFromModel();
    }//GEN-LAST:event_updateButtonActionPerformed
    
    /** Exit the Application */
    private void exitForm() {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        CategorizedInfoTestFrame f = new CategorizedInfoTestFrame();
        f.categorizedInfoPanel1.setModel(new wodka.test.CategorizedInfoTestModel());
        f.categorizedInfoPanel1.updateViewFromModel();
        f.setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private wodka.view.CategorizedInfoPanel categorizedInfoPanel1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
    
}
