/*
 * ModelInfoPanel.java
 *
 * Created on February 19, 2003, 9:30 PM
 */

package wodka.view;

/**
 * 
 * @author wolfi
 */
public class ModelInfoPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    public ModelInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {// GEN-BEGIN:initComponents
        modelResizePanel1 = new wodka.view.ModelResizePanel();
        infoTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 3,
                3, 3)));
        add(modelResizePanel1, java.awt.BorderLayout.CENTER);

        infoTextArea.setEditable(false);
        infoTextArea.setRows(3);
        infoTextArea.setFont(new java.awt.Font("Dialog", 0, 10));
        infoTextArea.setBackground(java.awt.Color.lightGray);
        add(infoTextArea, java.awt.BorderLayout.SOUTH);

    }// GEN-END:initComponents

    public void setModel(wodka.ga.model.Model s) {
        this.modelResizePanel1.setModel(s);
    }

    public void setInfo(String info) {
        this.infoTextArea.setText(info);
        this.infoTextArea.setCaretPosition(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea infoTextArea;

    private wodka.view.ModelResizePanel modelResizePanel1;
    // End of variables declaration//GEN-END:variables

}
